skip_local_validator = true

[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
state_counter = "87cNDwe79NtTGdd1YUBqJhmbZHkFWDpssvcHZrZ66Z93"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
